### ISSUE TITLE
utc_offset vs time_adjust?

### ISSUE THREAD

**Issue by cbode** [erczo/dendro-nosql-json#10]
Two schemas seem to label time offsets differently.   Are these supposed to be the same thing?  If so, I would assume 'utc_offset' would be the best label, but the value for PST would be -28800 in seconds.  

datastream.json	time_adjust	-28800	-8	hours
station.json	         utc_offset 	19800	5.5	hours

edit: is time_adjust to convert _to_ UTC from the sensor database?

**Comment by jscottsf** [comment]
This is my mistake. Actually, utc_offset should be -28800 for the PST stations (to achieve UTC-8). Sorry, the example is wrong. It's the UTC offset in seconds.

**Comment by cbode** [comment]
All examples have been corrected.
