### ISSUE TITLE
Need time zone on station

### ISSUE THREAD

**Issue by jscottsf** [erczo/dendro-nosql-json#11]
Please add a "time_zone" field to the schemas and seed data. For the schema, it should be a required string field. For the current stations, it should be set to "PST".

**Comment by cbode** [comment]
Is this redundant with "utc_offset"?  Can we merge the two? I have added "time_zone" for now and made it required in schema.  Examples have been updated to include "PST" as time_zone.  Need to confirm moment.js uses 3-digit timezone references and that it distinguishes between "PDT" and "PST".   Leaving this issue open for further discussion.

**Comment by cbode** [comment]
As per discussion:  "time_zone" currently used for display purposes, while "utc_offset" used for time.  Future effort to conflate the two in such a way to reflect Time Zone, without the daylight savings time.
