### ISSUE TITLE
Updates to media for station schema

### ISSUE THREAD

**Issue by jscottsf** [erczo/dendro-nosql-json#12]
Looking closer at the media object for datastreams, I'm proposing the following changes based on code I'm implementing.

```
  "media": [
    {
      "sizes": {
        "large": {
          "h": 800,
          "w": 400,
          "url": "http://..."
        },
        "medium": {},
        "medium_2x": {},
        "small": {},
        "small_2x": {},
        "thumb": {},
        "thumb_2x": {}
      },
      "type": "photo"
    }
  ],
```

I suggest we first create a reusable definition called "mediaSize", then use it for the various objects keys, ex: large, medium, etc.

The keys large, medium, small, and thumb should be required when media is present. The "_2x" variants are optional.

Note the the url was hoisted up into the size object.

**Comment by cbode** [comment]
Need some clarification on the schema definition.  Other than "h" and "w", what goes into the mediaSize object?   Below is current example with first and last sizes so far. 
```
"sizes": {
            "type": "object",
            "properties": {
              "large": {
                "type": "object",
                "properties": {
                  "h": {"type": "number"},
                  "w": {"type": "number"}
                }
              }, ...and many others between...
              "thumb_2x": {
                "type": "object",
                "properties": {
                  "h": {"type": "number"},
                  "w": {"type": "number"}
                }
              }
            },
            "required": ["large", "medium", "small","thumb"]
          },
```

**Comment by cbode** [comment]
mediaSize object created.
`"mediaSize": {
      "type": "object",
      "properties": {
        "h": {"type": "number"},
        "w": {"type": "number"}
      }
    }`
