### ISSUE TITLE
Attributes should be objects

### ISSUE THREAD

**Issue by cbode** [erczo/dendro-nosql-json#16]
I propose keeping with our standards for height, depth, and other attributes by making them objects, not just key:value pairs.   The reason is units.  Otherwise we need to type in "in" or "inches" or "m" or " m " or "meter" or "meters"  in addition to an offset.   Also should it be self-named (height height) or do we want an identifier, like "offset", which is used in odm2.  
OLD
  "attributes": {
      "height": "2 in"
  }
NEW
  "attributes": {
    "height": {
      "value": 2,
      "unit": "Inch"
    }
  }

**Comment by cbode** [comment]
Delta of two heights:  "Air Temp Delta Deg C 10m-2m Blue Oak Max"  dsid 3091

**Comment by Chris-Wong-1** [comment]
`"attributes": {
"delta": {
"begin": 2,
"end": 10,
"unit": "Meter"
}
}`

**Comment by cbode** [comment]
"attributes": { "delta": { 
"begin": "height": {
"value": 10,
"unit": "Meter"
}, 
"end":"height": {
"value": 2,
"unit": "Meter"
}
}
}

**Comment by Chris-Wong-1** [comment]
```
{
  "attributes": {
    "height": {
      "delta": true, 
      "value": [2, 10], 
      "unit": "Meter"
    }
  }
}
```

**Comment by jscottsf** [comment]
```
{
  "attributes": {
    "height": {
      "unit": "Inch",
      "value": [10, 2]
  }
}

```

**Comment by jscottsf** [comment]
```
{
  "attributes": {
    "height": {
      "unit": "Inch",
      "value": 10,
      "delta": [10, 2],
      "range": [10, 2]
  }
}
```
