### ISSUE TITLE
Add "count" to units

### ISSUE THREAD

**Issue by Chris-Wong-1** [erczo/dendro-nosql-json#17]
TDR frequency counts, thousands per second

**Comment by cbode** [comment]
Hertz is included in dt_Units.  Count is now included in ds_Variables.

**Comment by jscottsf** [comment]
We also have a term "Count" under the "dq" and "ds" Variable vocabularies. Perhaps the variable should be "Frequency" now?

**Comment by cbode** [comment]
We may need Frequency in the future, but not now.  For now, keeping "Count" in both dt-unit and in ds-variable.
