### ISSUE TITLE
Replace station website_url with an array of links

### ISSUE THREAD

**Issue by jscottsf** [erczo/dendro-nosql-json#21]
The website_url field on the station is limiting and what's really needed is a flexible way to add a few links to external sites for each station page. These links will appear before the "Contact station team" link. Thus, the website_url should be removed from the station schema and replaced with a structure such as:

```
    "external_links" : [ 
        {
            "title" : "Sensor database",
            "url" : "http://sensor.berkeley.edu/index_BORR.html"
        }, 
        {
            "title" : "Reserve website",
            "url" : "http://blueoakranchreserve.net"
        }
    ],
```

The field external_links should be optional; however if present, it must have at least one entry where the title and url are required.

**Comment by cbode** [comment]
Added to station.json schema.   jsonlint.com validates.  jsonschemalint.com complains a bit, but considers it valid.
