### ISSUE TITLE
derived_from_datastream_ids Should not be specified yet, must be Mongo ObjectID

### ISSUE THREAD

**Issue by jscottsf** [erczo/dendro-nosql-json#24]
The field "derived_from_datastream_ids" in the examples (seed data) should be excluded. It currently references a legacy ID and should reference other datastreams with a Mongo ObjectID. It will be the job of a admin tool to manage this so it's set correctly. For now, it's not needed for the dashboard to work.

**Comment by cbode** [comment]
Move legacy derived from datastream id to "description" as human readible only metadata.

**Comment by cbode** [comment]
Moved legacy derived from datastream id to "description" as human readable only metadata.
