### ISSUE TITLE
datapoints_config path is not correct for UCNRS datastreams

### ISSUE THREAD

**Issue by jscottsf** [erczo/dendro-nosql-json#25]
The path is currently "/legacy/datavalues", however, the path should resemble the table name where the values are stored. So rather, "/legacy/datavalues-ucnrs".

Here's a list of valid legacy service paths/endpoints (can all be verified with Postman):

```
/legacy/datavalues2
/legacy/datavalues-borr
/legacy/datavalues-motes
/legacy/datavalues-sagehen
/legacy/datavalues-seasonal
/legacy/datavalues-ucnrs
```

**Comment by cbode** [comment]
Derived datastreams already have correct path "/legacy/datavalues-seasonal".  UCNRS non-derived datastreams have been corrected to show "/legacy/datavalues-ucnrs".
