### ISSUE TITLE
Units for cumulative precipitation datastreams should be MillimeterPerHour / MillimeterPerDay

### ISSUE THREAD

**Issue by jscottsf** [erczo/dendro-nosql-json#31]
For the precipitation dashboard tiles, values are needed for Current Precipitation (mm/hr) and Yesterday’s Precipitation (mm/24hr). The units for these datastreams are currently `dt_Unit_Millimeter`. Should they not be a rate, such as `MillimeterPerHour` and `MillimeterPerDay`.

**Comment by cbode** [comment]
same response as for issue#32.   While this may be needed in the future, units at this time do not reference the time interval of the logger. So if rain is collected, it is simply millimeters of precipitation. The logger collects it every ten minutes. But that does not change the units to millimeters/tenminutes.
