### ISSUE TITLE
Need new rate units specified in dt-unit vocabulary

### ISSUE THREAD

**Issue by jscottsf** [erczo/dendro-nosql-json#32]
New units are needed for precipitation rates:

```
    {
      "abbreviation": "in/d",
      "definition": "TBD",
      "label": "InchPerDay",
      "name": "Inch Per Day"
    },
    {
      "abbreviation": "in/hr",
      "definition": "TBD",
      "label": "InchPerHour",
      "name": "Inch Per Hour"
    },
```

**Comment by cbode** [comment]
While this may be needed in the future, units at this time do not reference the time interval of the logger.   So if rain is collected, it is simply millimeters of precipitation.  The logger collects it every ten minutes.  But that does not change the units to millimeters/tenminutes.
